# Generated by Django 2.1.5 on 2019-09-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_definition', models.CharField(max_length=255)),
                ('foreign_definition', models.CharField(max_length=255)),
            ],
        ),
    ]
