# Generated by Django 2.1.5 on 2019-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='foreign_language',
            field=models.CharField(default='chian', max_length=255),
            preserve_default=False,
        ),
    ]
